name: score_counter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  wakelock_plus: ^1.1.4
  uuid: ^4.3.5
  live_activities: ^2.4.1
  basic_utils: ^5.8.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  generate: true  # Enable generation of localized strings
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

  # Configuration for Flutter localization
  assets:
    - lib/l10n/
